#!/bin/bash
# Script to test the layer-cake command-line tool.
# General stratgey is to run sub-commands, verify their
# outcomes, and print "END (PASS)". Anything else
# is a fail.
echo '--- CREATE'
python3 lyrck.py create
[[ -d .layer-cake ]] || exit 1
[[ -d .layer-cake/role/group ]] || exit 1
[[ -f .layer-cake/role/group/unique_id.json ]] || exit 1
[[ -f .layer-cake/role/group/start_stop.json ]] || exit 1
[[ -f .layer-cake/role/group/settings.json ]] || exit 1
[[ -f .layer-cake/role/group/log_storage.json ]] || exit 1
[[ -f .layer-cake/role/group/executable_file.json ]] || exit 1
python3 lyrck.py create && exit 1

python3 lyrck.py destroy
[[ ! -d .layer-cake ]] || exit 1
python3 lyrck.py destroy && exit 1

echo
echo '--- CREATE test-group'
python3 lyrck.py create test-group
[[ -d test-group ]] || exit 1
python3 lyrck.py create test-group && exit 1

python3 lyrck.py destroy test-group
[[ ! -d test-group ]] || exit 1
python3 lyrck.py destroy test-group && exit 1

echo
echo '--- CREATE retry'
python3 lyrck.py create test-group --retry='{"regular_steps": 8.0, "randomized": 0.25}'
[[ -d test-group ]] || exit 1

python3 lyrck.py destroy test-group
[[ ! -d test-group ]] || exit 1

echo
echo '--- ADD'
python3 lyrck.py create
python3 lyrck.py add test_server.py
[[ -d .layer-cake/role/test_server ]] || exit 1
[[ -f .layer-cake/role/test_server/unique_id.json ]] || exit 1
[[ -f .layer-cake/role/test_server/start_stop.json ]] || exit 1
[[ -f .layer-cake/role/test_server/settings.json ]] || exit 1
[[ -f .layer-cake/role/test_server/log_storage.json ]] || exit 1
[[ -f .layer-cake/role/test_server/executable_file.json ]] || exit 1
python3 lyrck.py add test_server.py && exit 1

python3 lyrck.py delete test_server
[[ ! -d .layer-cake/role/test_server ]] || exit 1

python3 lyrck.py destroy

echo
echo '--- ADD server_address'
python3 lyrck.py create
python3 lyrck.py add test_server.py --server_address='{"host": "127.0.0.1", "port": 50000}'
[[ -d .layer-cake/role/test_server ]] || exit 1
[[ -f .layer-cake/role/test_server/unique_id.json ]] || exit 1
[[ -f .layer-cake/role/test_server/start_stop.json ]] || exit 1
[[ -f .layer-cake/role/test_server/settings.json ]] || exit 1
[[ -f .layer-cake/role/test_server/log_storage.json ]] || exit 1
[[ -f .layer-cake/role/test_server/executable_file.json ]] || exit 1

[[ `cat .layer-cake/role/test_server/settings.json | grep 50000 | wc -l` -eq 1 ]] || exit 1

echo
echo '--- UPDATE server_address'
python3 lyrck.py update test_server --server_address='{"host": "127.0.0.1", "port": 50001}'

[[ `cat .layer-cake/role/test_server/settings.json | grep 50001 | wc -l` -eq 1 ]] || exit 1

python3 lyrck.py delete test_server
[[ ! -d .layer-cake/role/test_server ]] || exit 1

python3 lyrck.py destroy

echo
echo '--- ADD (COUNT)'
python3 lyrck.py create
python3 lyrck.py add test_publisher.py publisher
python3 lyrck.py add test_subscriber.py subscriber --count=10
[[ `python3 lyrck.py list | wc -l` -eq 11 ]] || exit 1

python3 lyrck.py delete subscriber-'[02468]'
[[ `python3 lyrck.py list | wc -l` -eq 6 ]] || exit 1

python3 lyrck.py delete --all
[[ `python3 lyrck.py list | wc -l` -eq 0 ]] || exit 1

python3 lyrck.py destroy

echo
echo '--- START'
python3 lyrck.py create
python3 lyrck.py add test_server.py server
python3 lyrck.py start
sleep 2
[[ `python3 lyrck.py status | wc -l` -eq 1 ]] || exit 1

python3 lyrck.py stop
python3 lyrck.py status && exit 1

python3 lyrck.py add test_subscriber.py subscriber --count=10
python3 lyrck.py start
sleep 2
[[ `python3 lyrck.py status | wc -l` -eq 11 ]] || exit 1

python3 lyrck.py stop
sleep 2
! python3 lyrck.py status || exit 1

python3 lyrck.py destroy

echo
echo '--- LOG'
python3 lyrck.py create
python3 lyrck.py add test_publisher.py publisher
python3 lyrck.py add test_subscriber.py subscriber --count=10
python3 lyrck.py start
sleep 2
[[ `python3 lyrck.py log publisher --rewind=10000 | grep "Received list_list_float" | wc -l` -eq 10 ]] || exit 1

python3 lyrck.py stop
python3 lyrck.py destroy

echo
echo '--- END (PASS)'
